In [17]:
!pip install --upgrade pandas==1.0.1

In [18]:
import pandas as pd
import numpy as np
pd.__version__

'1.0.1'

In [19]:
pd.options.display.float_format='{:.2f}'.format

In [20]:
np.set_printoptions(precision=1)

In [33]:
x1 = np.random.rand(2,5)*100
x1

array([[71.8, 37.5, 77.7, 91.6, 64.1],
       [95.7,  5.4, 35.7, 84.7, 63.3]])

In [22]:
x2 = np.random.randn(2,5)*-1
x2

array([[ 0.7,  0.1, -0.9, -0.3,  0.4],
       [-0. , -0.7, -1.3,  1.4, -1.1]])

In [23]:
np.concatenate([x1,x2])

array([[ 5.4e+00,  5.0e+01,  5.2e+01,  3.4e+01,  2.9e+01],
       [ 9.5e+01,  6.8e+01,  2.4e+01,  6.9e+01,  1.7e+01],
       [ 7.1e-01,  1.2e-01, -9.2e-01, -3.1e-01,  3.5e-01],
       [-2.7e-03, -7.3e-01, -1.3e+00,  1.4e+00, -1.1e+00]])

In [24]:
np.concatenate([x1,x2]).shape  #para vere que al concatenarlas pasaron de ser 2 matrice de 2*5 a una de 4*5

(4, 5)

In [25]:
np.concatenate([x1,x2], axis=1)  #concatena a traves de las columnas en vez de las filas

array([[ 5.4e+00,  5.0e+01,  5.2e+01,  3.4e+01,  2.9e+01,  7.1e-01,
         1.2e-01, -9.2e-01, -3.1e-01,  3.5e-01],
       [ 9.5e+01,  6.8e+01,  2.4e+01,  6.9e+01,  1.7e+01, -2.7e-03,
        -7.3e-01, -1.3e+00,  1.4e+00, -1.1e+00]])

In [27]:
np.concatenate([x1,x2], axis=1).shape

(2, 10)

In [36]:
s1 = pd.Series(x1[0],index=['a','b','c','d','e'])
s1

a   71.84
b   37.48
c   77.65
d   91.61
e   64.11
dtype: float64

In [38]:
s2 = pd.Series(x1[0],index=['c','d','e','f','g'])
s2

c   71.84
d   37.48
e   77.65
f   91.61
g   64.11
dtype: float64

In [41]:
pd.concat([s1,s2], axis=1)

0     1
a 71.84   nan
b 37.48   nan
c 77.65 71.84
d 91.61 37.48
e 64.11 77.65
f   nan 91.61
g   nan 64.11

In [43]:
pd.concat([s1,s2])

a   71.84
b   37.48
c   77.65
d   91.61
e   64.11
c   71.84
d   37.48
e   77.65
f   91.61
g   64.11
dtype: float64

In [44]:
s1.reset_index(drop=True)

0   71.84
1   37.48
2   77.65
3   91.61
4   64.11
dtype: float64

In [46]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0 71.84 71.84
1 37.48 37.48
2 77.65 77.65
3 91.61 91.61
4 64.11 64.11

In [47]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'],index=[0,1,2])
df1

a    b
0 1.53 4.64
1 9.86 3.76
2 5.58 6.28

In [48]:
df2 = pd.DataFrame(np.random.randn(3,2)*-1,columns=['a','b'],index=[2,3,4])
df2

a     b
2 -0.07 -0.60
3  0.74  0.47
4 -0.50 -0.04

In [49]:
pd.concat([df1,df2])

a     b
0  1.53  4.64
1  9.86  3.76
2  5.58  6.28
2 -0.07 -0.60
3  0.74  0.47
4 -0.50 -0.04

In [51]:
pd.concat([df1,df2],axis=1)

a    b     a     b
0 1.53 4.64   nan   nan
1 9.86 3.76   nan   nan
2 5.58 6.28 -0.07 -0.60
3  nan  nan  0.74  0.47
4  nan  nan -0.50 -0.04

In [52]:
pd.concat([df1,df2],axis=1,join='inner')  #funciona como sql, en este caso para la intersección

a    b     a     b
2 5.58 6.28 -0.07 -0.60

In [55]:
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ],axis=1)  #para unificar indices

a    b     a     b
0 1.53 4.64 -0.07 -0.60
1 9.86 3.76  0.74  0.47
2 5.58 6.28 -0.50 -0.04

In [57]:
df1.append(df2)

a     b
0  1.53  4.64
1  9.86  3.76
2  5.58  6.28
2 -0.07 -0.60
3  0.74  0.47
4 -0.50 -0.04

In [59]:
df1.append(df2).append(df2)

a     b
0  1.53  4.64
1  9.86  3.76
2  5.58  6.28
2 -0.07 -0.60
3  0.74  0.47
4 -0.50 -0.04
2 -0.07 -0.60
3  0.74  0.47
4 -0.50 -0.04

In [61]:
df1.T  #traspuesta columnas y filas invertidas

0    1    2
a 1.53 9.86 5.58
b 4.64 3.76 6.28

In [64]:
df1.T.append(df2.T)

0    1     2    3     4
a 1.53 9.86  5.58  nan   nan
b 4.64 3.76  6.28  nan   nan
a  nan  nan -0.07 0.74 -0.50
b  nan  nan -0.60 0.47 -0.04

In [65]:
df1.T.append(df2.T).T

a    b     a     b
0 1.53 4.64   nan   nan
1 9.86 3.76   nan   nan
2 5.58 6.28 -0.07 -0.60
3  nan  nan  0.74  0.47
4  nan  nan -0.50 -0.04